# Generated by Django 5.1.1 on 2024-09-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(blank=True, max_length=10, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.CharField(blank=True, max_length=10, null=True)),
                ('instrument_token', models.CharField(blank=True, max_length=20, null=True)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buy_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overnight_quantity', models.IntegerField(blank=True, null=True)),
                ('day_buy_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day_buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overnight_buy_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overnight_buy_quantity', models.IntegerField(blank=True, null=True)),
                ('day_buy_quantity', models.IntegerField(blank=True, null=True)),
                ('day_sell_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day_sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day_sell_quantity', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unrealised', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('realised', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sell_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tradingsymbol', models.CharField(blank=True, max_length=20, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
