# Generated by Django 5.1.1 on 2024-09-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnoappbe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=10, null=True)),
                ('tradingsymbol', models.CharField(blank=True, max_length=50, null=True)),
                ('instrument_token', models.CharField(blank=True, max_length=20, null=True)),
                ('order_type', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('exchange_timestamp', models.DateTimeField(blank=True, null=True)),
                ('average_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='position',
            name='exchange',
        ),
    ]
