# Generated by Django 5.1.1 on 2024-09-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnoappbe', '0002_trade_remove_position_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='order_id',
        ),
    ]
